[package]
name = "dvb_gse_tunnel"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio-tun = "0.11.5"
tokio = { version = "1.0", features = ["full"] }

[[bin]]
name = "satencap"
path = "src/satencap.rs"


[[bin]]
name = "satdecap"
path = "src/satdecap.rs"
